"""tirei a coluna telefone

Revision ID: 215f0592bb61
Revises: 232d895432bc
Create Date: 2025-10-02 08:05:32.147826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215f0592bb61'
down_revision = '232d895432bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
